apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
  namespace: roboshop
data:
    RABBITMQ_DEFAULT_USER: roboshop
    RABBITMQ_DEFAULT_PASS: roboshop123
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    project: roboshop
    environment: dev
    tier: db
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    project: roboshop
    environment: dev
    tier: db
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      tier: db
  serviceName: "rabbitmq-headless"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        tier: db
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        envFrom:
        - configMapRef:
            name: rabbitmq
        volumeMounts:
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi